# Starter game. Copy this directory, change NAME and FOLDER, and edit hello.c.
#   make                               build
#   make install IPOD=/Volumes/MyiPod  copy to the iPod

# Point this to the SDK
EAPP_SDK := ../..

# Name of the game
NAME     := Hello

# ID of the game - must be unique for games
FOLDER   := 484F4D4548454C4F

# List of source files
SRCS     := hello.c

include $(EAPP_SDK)/eapp.mk
