#!/usr/bin/env python3
"""Generate the eApp import records (ARM assembly) for a list of OS modules.

    mkimports.py OUT.S Module [Module ...]

Record layout expected by the OS loader:
    +0x00 char name[32]     module name, NUL padded
    +0x20 u8   uuid[16]     interface UUID
    +0x30 u32  count        must equal the OS module's function count
    +0x34 u32  next         absolute address of the next record, or 0
    +0x38 count x "ldr pc, [pc, #4*count-8]"  (one stub per function, callable by name)
          count x .word 0   (literal pool, patched by the loader in table order)
          .word 0x29061968  (end-of-stubs sentinel)
The first record is exported as `eapp_imports` and goes in the image header.
"""

# Created by an LLM

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from modules import MODULES  # noqa: E402

STUB_END = 0x29061968


def record(name, next_label):
    mod = MODULES[name]
    funcs = mod["funcs"]
    n = len(funcs)
    uuid = bytes.fromhex(mod["uuid"])
    lines = [
        "",
        "@ ---- %s: %d functions ----" % (name, n),
        "    .align 2",
        "eapp_import_%s:" % name,
        '    .ascii "%s"' % name,
        "    .space %d" % (32 - len(name)),
        "    .byte " + ",".join("0x%02x" % b for b in uuid),
        "    .word %d" % n,
        "    .word %s" % (next_label or "0"),
    ]
    for f in funcs:
        lines += ["    .global %s" % f, "    .type %s, %%function" % f,
                  "%s:" % f, "    ldr pc, [pc, #%d]" % (4 * n - 8)]
    lines += ["    .word 0" for _ in funcs]
    lines.append("    .word 0x%08x" % STUB_END)
    return lines


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    out, names = sys.argv[1], sys.argv[2:]
    for n in names:
        if n not in MODULES:
            sys.exit("unknown module %r (known: %s)" % (n, ", ".join(MODULES)))
    body = ["@ Generated by tools/mkimports.py -- do not edit.",
            "    .arm",
            '    .section .eapp_imports, "ax", %progbits',
            "    .global eapp_imports",
            "eapp_imports = eapp_import_%s" % names[0]]
    for i, n in enumerate(names):
        nxt = "eapp_import_%s" % names[i + 1] if i + 1 < len(names) else None
        body += record(n, nxt)
    body.append('    .section .note.GNU-stack, "", %progbits')
    with open(out, "w") as f:
        f.write("\n".join(body) + "\n")


if __name__ == "__main__":
    main()
